server:
  port: 8081
  servlet:
    context-path: /authserver
spring:
  application:
    name: authserver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    
logging:
  file:
    path: logs/
    name: logs/application.log

springfox:
  documentation:
    swagger-ui:
      enabled: true
    webjars:
      enabled: true
    swagger.v2.path: /api-docs