server:
  port: 8082
  servlet:
    context-path: /portpolioservice
#    ribbon:
#      eureka:
#        enabled: true
spring:
  application:
    name: portpolioservice
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
    output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
logging:
  file:
    path: logs/
    name: logs/application.log

springfox:
  documentation:
    swagger-ui:
      enabled: true
    webjars:
      enabled: true
    swagger.v2.path: /api-docs
    
#stocktradeservice:
#  ribbon:
#    listOfServers: http://localhost:8080, http://localhost:8085

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 160000000
        read-timeout: 160000000