server:
  port: 8083
  servlet:
    context-path: /stocktradeservice
#  ribbon:
#    eureka:
#      enabled: true
spring:
  application:
    name: stocktradeservice
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
#  instance:
#    instanceId: ${spring.application.name}:${random.value}
      
logging:
  file:
    path: logs/
    name: logs/application.log

springfox:
  documentation:
    swagger-ui:
      enabled: true
    webjars:
      enabled: true
    swagger.v2.path: /api-docs
    
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 160000000
        read-timeout: 160000000
    
#feign:
#  circuitbreaker:
#    enabled: true